### ISSUE TITLE
Support for the 9inch7 display

### ISSUE THREAD

**Issue by funtogether** [soonuse/epd-library-python#8]
@soonuse Do you think it is possible to adapt for example `epd7in5.py` to support the 9inch7 variant from waveshare? Or in other words which files must be customized to meet the specifications for the 9.7 inch display?

**Comment by nickzhe** [comment]
@funtogether @soonuse the 7.5 and 6.0/9.7 inch hat uses different type of driver board, IT8951, the product website did not provide a python driver for this. I am also thinking of getting a python version for this, it will be alot of help, thanks!

**Comment by er-minio** [comment]
> uses different type of driver board, IT8951

Same poroblem here. Trying control a 6.0 inch Waveshare e-paper display using python.

**Comment by danielneumann** [comment]
@funtogether @nickzhe @er-minio I stumbled across this repo providing IT8951 resources based referncing a 6.0 inch display:
https://github.com/GregDMeyer/IT8951 

I try to get it working with my 9.7

**Comment by danielneumann** [comment]
PR https://github.com/soonuse/epd-library-python/pull/14

**Comment by er-minio** [comment]
@danielneumann thanks!
I got that working! Can confirm 6" display works fine with https://github.com/GregDMeyer/IT8951

**Comment by cromulus** [comment]
Sorry, I'm relatively new to python.

Quick question, How do you install the IT8951 library included in this repository?

It doesn't have a `setup.py` or a `pyproject.toml` file.

Thanks!

**Comment by JeanB51** [comment]
@cromulus  Did you get an answer to this ? . I have the same question..

**Comment by cromulus** [comment]
Nope. I just ended up hacking on the provided C program from waveshare, making it a CLI interface and calling it with a shell exec.

Suboptimal, but hey, it works.

**Comment by QA71** [comment]
Hello I'm new to programming and i want to connect 7.8 ws with rPİ. And I know a little python.  So can anyone explain me step by step how to setup this.
Final program will write some data on ePaper as quick as possible using Python code. Also i want to use Partial refresh.
Thank you

**Comment by QA71** [comment]
> Nope. I just ended up hacking on the provided C program from waveshare, making it a CLI interface and calling it with a shell exec.
> 
> Suboptimal, but hey, it works.

Can you please upload the the files?
I'm trying with 7.8 inch ws

**Comment by JeanB51** [comment]
follow the instructions:
   To install, clone the repository, enter the directory and run
       pip install -r requirements.txt
       pip install ./

Worked for me, for a 7.8" screen on RPi 3 and pi zero w also.

Watch how you plus the flat cable, upside down it wont work. 
Once yyou get it working, alle the test programs work as advertised.

**Comment by QA71** [comment]
Thank you all

what i have done is this
- install new OS on a rPi Zero (NOOBS_v3_0_0)
- pi@raspberrypi:~ $ sudo git clone https://github.com/soonuse/epd-library-python.git
- pi@raspberrypi:~ $ sudo git clone https://github.com/GregDMeyer/IT8951.git
- pi@raspberrypi:~ $ sudo pip install Pillow
- pi@raspberrypi:~/IT8951 $ sudo pip install -r requirements.txt
          Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
          Requirement already satisfied: pillow in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
- pi@raspberrypi:~/IT8951 $ pip install ./
          Processing /home/pi/IT8951
               Complete output from command python setup.py egg_info:
               Traceback (most recent call last):
                   File "<string>", line 1, in <module>
                   File "/tmp/pip-3yXkvS-build/setup.py", line 8, in <module>
                       raise RuntimeError("This module is written for Python 3.")
               RuntimeError: This module is written for Python 3.
               ----------------------------------------
         Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-3yXkvS-build/

So i used
- pi@raspberrypi:~/IT8951 $ sudo pip3 install ./
          Successfully installed IT8951-0.1.0
- python3 test.py
          ImportError: cannot import name 'ImageTk'

so i tried
- pi@raspberrypi:~ $ sudo apt-get install python3-pil python3-pil.imagetk
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    python3-pil is already the newest version (4.0.0-4).
    python3-pil set to manually installed.
    Suggested packages:
      python-pil-doc python3-pil.imagetk-dbg
    The following NEW packages will be installed:
     python3-pil.imagetk
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 55.2 kB of archives.
   After this operation, 80.9 kB of additional disk space will be used.
   Do you want to continue? [Y/n] y
   Err:1 http://raspbian.raspberrypi.org/raspbian stretch/main armhf python3-pil.imagetk armhf 4.0.0-4
      404  Not Found [IP: 93.93.128.193 80]
    E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/pillow/python3-pil.imagetk_4.0.0-4_armhf.deb  404  
    Not Found [IP: 93.93.128.193 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

so 
- sudo apt-get update
- sudo apt-get grade

AND FINALY WORKED...
pi@raspberrypi:~/epd-library-python/9.7inch_e-paper/raspberrypi/python $ python3 main.py

**Comment by ErikBrewster** [comment]
@galev00 Thank you for writing that out. It must have saved me hours. I was able to get my RPi4 with a 9.7" display working by following your procedure.
